# Generated by Django 4.2 on 2024-03-18 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
