# Generated by Django 4.2 on 2024-03-18 03:54

import computer_store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computer_store', '0002_delete_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=computer_store.models.upload_to)),
                ('price', models.IntegerField()),
                ('created_by', models.CharField(max_length=200)),
                ('created_date', models.DateField()),
                ('modified_date', models.DateField()),
            ],
        ),
    ]
