# Generated by Django 4.2 on 2024-03-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='star_review',
            field=models.IntegerField(default=0),
        ),
    ]
