# Generated by Django 4.2 on 2024-03-27 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0005_cartmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
