# Generated by Django 4.2 on 2024-03-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0007_cartmodel'),
    ]

    operations = [
        migrations.RunSQL('CREATE OR REPLACE FUNCTION tes48() RETURNS TABLE(c_id integer, c_username varchar) LANGUAGE "plpgsql" AS $$ BEGIN return query select id, username from auth_user; end; $$')
    ]
