# Generated by Django 4.2 on 2024-03-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0008_auto_20240330_1601'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION tes49()
            RETURNS TABLE(c_id integer, c_username varchar)
            LANGUAGE "plpgsql"
            AS $$
            BEGIN 
                return query 
                    select id, username 
                    from auth_user; 
            end; 
            
            $$           
            """
        )
    ]
