# Generated by Django 4.2 on 2024-04-01 02:58
# author: pakusadewa
# date  : 1 April 2024
# change: Add new function to get all cart product by user id

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0012_auto_20240401_1053'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION cart_get_all_by_user_id_1(t_user_id int)
            RETURNS TABLE(t_name varchar, t_image_url varchar, price int, t_total_order int)
            LANGUAGE "plpgsql"
            AS $$
            BEGIN 
                return query 
                    SELECT 
                        p.name, 
                        p.image_url,
                        p.price,
                        c.total_order 
                    FROM public.computer_store_productmodel AS p 
                    INNER JOIN public.computer_store_cartmodel AS c ON p.id = c.product_id
                    WHERE c.user_id = t_user_id;
            end;
            $$ 
            """
        )
    ]
